apiVersion: v1
kind: Deployment
metadata:
  name: my-app
    labels:
      app: mongo
      version: "v1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo
      version: "v1"
  template:
    metadata:
      labels:
        app: mongo
        version: "v1"
    spec:
      containers:
      - name: mongo-app
      image: nginx
      ports:
      - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: mongo
    version: "v1"
  ports:
  - protocol: TCP
  port: 8080
  targetPort: 27017
      
